# Generated by Django 3.0.5 on 2020-04-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=3000)),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
